### ISSUE TITLE
About the result of the example img 000000.jpg

### ISSUE THREAD

**Issue by Randy-1009** [intel/handwritten-chinese-ocr-samples#7]
Why the last several words can not be recognized?
It's because the program self or some length limit?
![000000](https://user-images.githubusercontent.com/46707940/146519974-08f5afca-c15f-4307-8cac-669b39c8eca1.jpg)

**Comment by Randy-1009** [comment]
The result is "仍有“铁马冰河入梦来”的情怀，一生心忧天", where is "下，被世人所"

**Comment by bliu3650** [comment]
> Why the last several words can not be recognized? It's because the program self or some length limit? ![000000](https://user-images.githubusercontent.com/46707940/146519974-08f5afca-c15f-4307-8cac-669b39c8eca1.jpg)

You're right. Our previous released models (for SCUT-EPT dataset) had a limitation on the length of input, because of the deployment tool (openvino) which required the fixed length.

For this 000000.jpg sample, with 1318x48 resolution, we firstly resized it to 2636x96, and ignored the last 636 (=2636-2000) columns. So in the prediction, you can not see that "下，被世人所". But of course, you can remove that limitation by regenerating the model (bin/xml) and setting length as long as you need for deployment with OpenVINO.

**Comment by Randy-1009** [comment]
> 

Thank you!
